kind: Service 
apiVersion: v1 
metadata:
  name: nginx-svc
spec:
  type: NodePort
  selector:
    app: nginx

  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    - nodePort: 31004
      port: 80
      targetPort: 80